// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class BoxCrackerKaynak
{
        public const string achievement_10000_boxes = "CgkI1p743fUHEAIQAg"; // <GPGSID>
        public const string achievement_great_again = "CgkI1p743fUHEAIQCQ"; // <GPGSID>
        public const string achievement_one_giant_leap_for_mankind = "CgkI1p743fUHEAIQBQ"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkI1p743fUHEAIQAw"; // <GPGSID>
        public const string achievement_50000_boxes = "CgkI1p743fUHEAIQDw"; // <GPGSID>
        public const string achievement_not_bad = "CgkI1p743fUHEAIQCg"; // <GPGSID>
        public const string achievement_answer_to_life_the_universe_and_everything = "CgkI1p743fUHEAIQBw"; // <GPGSID>
        public const string achievement_100000_boxes = "CgkI1p743fUHEAIQEA"; // <GPGSID>
        public const string achievement_that_is_one_small_step_for_man = "CgkI1p743fUHEAIQBA"; // <GPGSID>
        public const string achievement_retard_alert = "CgkI1p743fUHEAIQCA"; // <GPGSID>
        public const string achievement_25000_boxes = "CgkI1p743fUHEAIQDg"; // <GPGSID>
        public const string achievement_a_toast_for_you = "CgkI1p743fUHEAIQDA"; // <GPGSID>
        public const string achievement_success = "CgkI1p743fUHEAIQCw"; // <GPGSID>
        public const string achievement_impossible = "CgkI1p743fUHEAIQDQ"; // <GPGSID>
        public const string achievement_1000_boxes = "CgkI1p743fUHEAIQAQ"; // <GPGSID>
        public const string achievement_there_is_a_snake_inside = "CgkI1p743fUHEAIQBg"; // <GPGSID>

}

